//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.11 at 12:55:30 PM CET 
//


package fedora.server.config.pep;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the melcoe.fedora.pep.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CacheSize_QNAME = new QName("", "cache-size");
    private final static QName _CacheItemTtl_QNAME = new QName("", "cache-item-ttl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: melcoe.fedora.pep.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EvaluationEngine }
     * 
     */
    public EvaluationEngine createEvaluationEngine() {
        return new EvaluationEngine();
    }

    /**
     * Create an instance of {@link PdpClient }
     * 
     */
    public PdpClient createPdpClient() {
        return new PdpClient();
    }

    /**
     * Create an instance of {@link HandlersObjects }
     * 
     */
    public HandlersObjects createHandlersObjects() {
        return new HandlersObjects();
    }

    /**
     * Create an instance of {@link HandlersRest }
     * 
     */
    public HandlersRest createHandlersRest() {
        return new HandlersRest();
    }

    /**
     * Create an instance of {@link HandlersWs }
     * 
     */
    public HandlersWs createHandlersWs() {
        return new HandlersWs();
    }

    /**
     * Create an instance of {@link RelationshipResolver }
     * 
     */
    public RelationshipResolver createRelationshipResolver() {
        return new RelationshipResolver();
    }

    /**
     * Create an instance of {@link ResponseCache }
     * 
     */
    public ResponseCache createResponseCache() {
        return new ResponseCache();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link PEPConfig }
     * 
     */
    public PEPConfig createConfig() {
        return new PEPConfig();
    }

    /**
     * Create an instance of {@link Handler }
     * 
     */
    public Handler createHandler() {
        return new Handler();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cache-size")
    public JAXBElement<BigInteger> createCacheSize(BigInteger value) {
        return new JAXBElement<BigInteger>(_CacheSize_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cache-item-ttl")
    public JAXBElement<BigInteger> createCacheItemTtl(BigInteger value) {
        return new JAXBElement<BigInteger>(_CacheItemTtl_QNAME, BigInteger.class, null, value);
    }

}
