//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.11 at 12:55:30 PM CET 
//


package fedora.server.config.pep;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pdp-client"/>
 *         &lt;element ref="{}response-cache"/>
 *         &lt;element ref="{}relationship-resolver"/>
 *         &lt;element ref="{}evaluation-engine"/>
 *         &lt;element ref="{}handlers-rest"/>
 *         &lt;element ref="{}handlers-objects"/>
 *         &lt;element ref="{}handlers-ws" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pdpClient",
    "responseCache",
    "relationshipResolver",
    "evaluationEngine",
    "handlersRest",
    "handlersObjects",
    "handlersWs"
})
@XmlRootElement(name = "config")
public class PEPConfig {

    @XmlElement(name = "pdp-client", required = true)
    protected PdpClient pdpClient;
    @XmlElement(name = "response-cache", required = true)
    protected ResponseCache responseCache;
    @XmlElement(name = "relationship-resolver", required = true)
    protected RelationshipResolver relationshipResolver;
    @XmlElement(name = "evaluation-engine", required = true)
    protected EvaluationEngine evaluationEngine;
    @XmlElement(name = "handlers-rest", required = true)
    protected HandlersRest handlersRest;
    @XmlElement(name = "handlers-objects", required = true)
    protected HandlersObjects handlersObjects;
    @XmlElement(name = "handlers-ws", required = true)
    protected List<HandlersWs> handlersWs;

    /**
     * Gets the value of the pdpClient property.
     * 
     * @return
     *     possible object is
     *     {@link PdpClient }
     *     
     */
    public PdpClient getPdpClient() {
        return pdpClient;
    }

    /**
     * Sets the value of the pdpClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link PdpClient }
     *     
     */
    public void setPdpClient(PdpClient value) {
        this.pdpClient = value;
    }

    /**
     * Gets the value of the responseCache property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseCache }
     *     
     */
    public ResponseCache getResponseCache() {
        return responseCache;
    }

    /**
     * Sets the value of the responseCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseCache }
     *     
     */
    public void setResponseCache(ResponseCache value) {
        this.responseCache = value;
    }

    /**
     * Gets the value of the relationshipResolver property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipResolver }
     *     
     */
    public RelationshipResolver getRelationshipResolver() {
        return relationshipResolver;
    }

    /**
     * Sets the value of the relationshipResolver property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipResolver }
     *     
     */
    public void setRelationshipResolver(RelationshipResolver value) {
        this.relationshipResolver = value;
    }

    /**
     * Gets the value of the evaluationEngine property.
     * 
     * @return
     *     possible object is
     *     {@link EvaluationEngine }
     *     
     */
    public EvaluationEngine getEvaluationEngine() {
        return evaluationEngine;
    }

    /**
     * Sets the value of the evaluationEngine property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvaluationEngine }
     *     
     */
    public void setEvaluationEngine(EvaluationEngine value) {
        this.evaluationEngine = value;
    }

    /**
     * Gets the value of the handlersRest property.
     * 
     * @return
     *     possible object is
     *     {@link HandlersRest }
     *     
     */
    public HandlersRest getHandlersRest() {
        return handlersRest;
    }

    /**
     * Sets the value of the handlersRest property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlersRest }
     *     
     */
    public void setHandlersRest(HandlersRest value) {
        this.handlersRest = value;
    }

    /**
     * Gets the value of the handlersObjects property.
     * 
     * @return
     *     possible object is
     *     {@link HandlersObjects }
     *     
     */
    public HandlersObjects getHandlersObjects() {
        return handlersObjects;
    }

    /**
     * Sets the value of the handlersObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlersObjects }
     *     
     */
    public void setHandlersObjects(HandlersObjects value) {
        this.handlersObjects = value;
    }

    /**
     * Gets the value of the handlersWs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the handlersWs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHandlersWs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HandlersWs }
     * 
     * 
     */
    public List<HandlersWs> getHandlersWs() {
        if (handlersWs == null) {
            handlersWs = new ArrayList<HandlersWs>();
        }
        return this.handlersWs;
    }

}
