package fedora.server.storage;

/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2002</p>
 * <p>Company: </p>
 * @author unascribed
 * @version 1.0
 */

import fedora.server.management.*;
import java.io.InputStream;

public abstract class ObjectWriter
{

  public ObjectWriter(String objectPID)
  {
  }

  /**
   * Methods that pertain to the digital object entity as a whole
   */

    public abstract String putObject(byte[] objectXML);

    public abstract String putObject(InputStream objectXML);

    public abstract void deleteObject();

    public abstract void withdrawObject();

  /**
   * Methods that pertain to the digital object components
   */

    // Should these methods assume that the API-M level puts
    // things together into components already (i.e., take
    // something like a Datastream object as parameter, or should
    // these methods reflect the individual parms as in API-M?

    public abstract String setObjectPID();

    public abstract void setObjectLabel(String label);

    public abstract void setObjectContentModelID(String cmodID);

    public abstract void setObjectAgent(Agent agents);

  /**
    * @param   array of Datastream components
    * @return  array of datastreamIDs generated by storage subsystem
    */
    public abstract String[] addDatastreams(Datastream[] datastreams);

    public abstract String addDatastream(String datastreamID);

    public abstract String[] addDisseminators(Disseminator[] disseminators);

    public abstract String addDisseminator(Disseminator disseminator);

  /**
   * System metadata that is managed by system
     */
    protected abstract void setObjectCreateDateTime();

    protected abstract void setObjectModDataTime();

    protected abstract void setObjectState();

    protected abstract void setObjectAuditTrail(AuditRecord audRec);
}