package fedora.server.management;

import java.io.*;

/**
 * Interface for generating Fedora PIDs.
 *
 * @author cwilper@cs.cornell.edu (first version, Paul Charlton)
 * @version $Id$
 */
public interface PIDGenerator {

    /**
     * Generate a new pid that is guaranteed to be unique, within the
     * given namespace.
     */
    public String generatePID(String NamespaceID) throws IOException;

    /**
     * Get the last pid that was generated.
     */
    public String getLastPID() throws IOException;

    /**
     * Cause the given PID to never be generated by the PID generator.
     */
    public void neverGeneratePID(String pid) throws IOException;
}
