#!/bin/sh

if [ "$FEDORA_HOME" = "" ]; then
  echo "ERROR: Environment variable FEDORA_HOME must be set."
  exit 1
fi

(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/bdef-mrsid-image-picksize.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/bdef-mrsid-image.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/bdef-simple-image.xml "first import")

(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/bmech-mrsid-image-picksize.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/bmech-mrsid-image.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/bmech-simple-image.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/bmech-sizer-image.xml "first import")

(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/obj-mrsid-image-picksize.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/obj-mrsid-image.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/obj-simple-image.xml "first import")
(exec java -Xms64m -Xmx96m -cp $FEDORA_HOME/client:$FEDORA_HOME/client/client.jar -Dfedora.home=$FEDORA_HOME fedora.client.ingest.AutoIngestor localhost 8080 $FEDORA_HOME/demo/obj-sizer-image.xml "first import")

exit 0
